default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: lab6-dev
  username: postgres
  password:
  host: db
# Increased timeout because of local deployment issues
  timeout: 10000

test:
  <<: *default
  database:

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  database: web615-lab6
  username: lab6
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
